template-file-path: ./vpc-multiaz-stack.yaml
parameters:
  StudentName: "Eugene Anokye"
  LabName: "Multi-AZ VPC Lab"
tags:
  Project: MultiAZ-VPC-Lab
  Environment: Lab
  ManagedBy: CloudFormation-GitSync

  region